from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Any

from common import (
    extract_tag_refs,
    html_to_text,
    normalize_math_text,
    parse_changed_tags_file,
    read_jsonl,
    sha256_text,
    write_jsonl,
)
from runtime_utils import prefetch_config, setup_logging


ENV_CLASS_RE = re.compile(r'class="env-([a-zA-Z0-9\-]+)"')
REFERENCE_RE = re.compile(r'data-tag="[0-9A-Z]{4}">([^<]+)</span>')
TITLE_RE = re.compile(r"<h[1-6][^>]*>(.*?)</h[1-6]>", re.IGNORECASE | re.DOTALL)
LOGGER = logging.getLogger("build_corpus")


def parse_structure(content: str) -> dict[str, Any]:
    if not content:
        return {}
    text = content.strip()
    if not text or text.startswith("This tag does not have a structure."):
        return {}
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass
    return {}


def clean_inline_html(fragment: str) -> str:
    return html_to_text(fragment)


def infer_env_type(statement_html: str, env_hint: str) -> str:
    match = ENV_CLASS_RE.search(statement_html or "")
    if match:
        return match.group(1).lower()
    return env_hint.lower() if env_hint else "unknown"


def infer_reference(structure: dict[str, Any], statement_html: str) -> str:
    reference = str(structure.get("reference", "")).strip()
    if reference:
        return reference
    match = REFERENCE_RE.search(statement_html or "")
    if match:
        return clean_inline_html(match.group(1))
    return ""


def infer_title(structure: dict[str, Any], statement_html: str) -> str:
    name = str(structure.get("name", "")).strip()
    if name:
        return name
    match = TITLE_RE.search(statement_html or "")
    if match:
        return clean_inline_html(match.group(1))
    return ""


def split_statement_and_proof(statement_text: str, full_text: str) -> tuple[str, str]:
    st = statement_text.strip()
    ft = full_text.strip()
    if not ft:
        return st, ""
    if st and ft.startswith(st):
        proof = ft[len(st) :].strip()
        return st, proof
    return st, ft if st != ft else ""


def parse_args() -> argparse.Namespace:
    config_path, cfg = prefetch_config("build_corpus")
    parser = argparse.ArgumentParser(
        description=(
            "Build unified retrieval corpus from metadata + API cache with incremental update."
        )
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=config_path,
        help="Path to JSON/YAML config.",
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default=str(cfg.get("log_level", "INFO")),
        help="Log level: DEBUG|INFO|WARNING|ERROR",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=Path(str(cfg.get("metadata", "data/processed/tag_metadata.jsonl"))),
        help="Metadata JSONL generated by parse_tex.py",
    )
    parser.add_argument(
        "--api-dir",
        type=Path,
        default=Path(str(cfg.get("api_dir", "data/raw/api/tags"))),
        help="Per-tag API JSON directory from fetch_api.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(str(cfg.get("output", "data/processed/corpus.jsonl"))),
        help="Output corpus JSONL path.",
    )
    parser.add_argument(
        "--edges-output",
        type=Path,
        default=Path(str(cfg.get("edges_output", "data/processed/ref_edges.jsonl"))),
        help="Output citation edges JSONL path.",
    )
    parser.add_argument(
        "--changed-tags-file",
        type=Path,
        default=Path(str(cfg.get("changed_tags_file", "data/raw/api/changed_tags.json"))),
        help="JSON file containing changed tag list used in incremental mode.",
    )
    parser.add_argument(
        "--incremental",
        action="store_true",
        default=bool(cfg.get("incremental", False)),
        help="Merge updates into existing corpus instead of rebuilding everything.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    setup_logging(args.log_level)
    metadata_rows = list(read_jsonl(args.metadata))
    if not metadata_rows:
        raise RuntimeError(f"No metadata rows found in {args.metadata}. Run parse_tex.py first.")

    metadata_by_tag = {row["tag"]: row for row in metadata_rows if row.get("tag")}
    changed_tags = parse_changed_tags_file(args.changed_tags_file)
    existing_by_tag: dict[str, dict[str, Any]] = {}
    if args.incremental and args.output.exists():
        existing_by_tag = {row["tag"]: row for row in read_jsonl(args.output) if row.get("tag")}

    if args.incremental:
        target_tags = set(changed_tags)
        if not target_tags:
            LOGGER.info("Incremental mode with no changed tags; keeping existing corpus.")
            final_rows = sorted(existing_by_tag.values(), key=lambda x: x["tag"])
            write_jsonl(args.output, final_rows)
            edge_rows = []
            for row in final_rows:
                for ref in row.get("outgoing_refs", []):
                    edge_rows.append(
                        {"source_tag": row["tag"], "target_tag": ref, "edge_type": "refers_to"}
                    )
            write_jsonl(args.edges_output, edge_rows)
            LOGGER.info("Wrote %d corpus rows -> %s", len(final_rows), args.output)
            LOGGER.info("Wrote %d edges -> %s", len(edge_rows), args.edges_output)
            return 0
    else:
        target_tags = set(metadata_by_tag.keys())

    updated_tags = 0
    removed_tags = 0
    for tag in sorted(target_tags):
        row = metadata_by_tag.get(tag)
        if row is None:
            if tag in existing_by_tag:
                del existing_by_tag[tag]
                removed_tags += 1
            continue

        tag = row["tag"]
        api_path = args.api_dir / f"{tag}.json"
        if not api_path.exists():
            if tag in existing_by_tag:
                del existing_by_tag[tag]
                removed_tags += 1
            continue

        payload = json.loads(api_path.read_text(encoding="utf-8", errors="replace"))
        structure = parse_structure(payload.get("structure", {}).get("content", ""))
        statement_html = payload.get("statement", {}).get("content", "") or ""
        full_html = payload.get("full", {}).get("content", "") or ""

        statement_text = html_to_text(statement_html)
        full_text = html_to_text(full_html)
        statement_text, proof_text = split_statement_and_proof(statement_text, full_text)

        normalized_text = normalize_math_text(f"{statement_text}\n{proof_text}".strip())
        outgoing_refs = extract_tag_refs(full_html)
        env_type = infer_env_type(statement_html, row.get("env_hint", "unknown"))
        reference = infer_reference(structure, statement_html)
        title = infer_title(structure, statement_html)
        content_hash = sha256_text(
            "\n".join([statement_text, proof_text, full_html, statement_html, row.get("full_label", "")])
        )

        corpus_row = {
            "id": tag,
            "tag": tag,
            "full_label": row.get("full_label", ""),
            "chapter_key": row.get("chapter_key", ""),
            "source_tex": row.get("source_tex", ""),
            "env_type": env_type,
            "reference": reference,
            "title": title,
            "structure_type": structure.get("type", ""),
            "structure_name": structure.get("name", ""),
            "statement_text": statement_text,
            "proof_text": proof_text,
            "normalized_text": normalized_text,
            "outgoing_refs": outgoing_refs,
            "statement_html": statement_html,
            "full_html": full_html,
            "content_hash": content_hash,
            "api_content_hash": payload.get("content_hash", ""),
        }
        existing_by_tag[tag] = corpus_row
        updated_tags += 1

    if not args.incremental:
        # Full rebuild should not keep stale tags.
        existing_by_tag = {k: v for k, v in existing_by_tag.items() if k in metadata_by_tag}

    final_rows = sorted(existing_by_tag.values(), key=lambda x: x["tag"])
    edge_rows: list[dict[str, str]] = []
    for row in final_rows:
        for ref in row.get("outgoing_refs", []):
            edge_rows.append({"source_tag": row["tag"], "target_tag": ref, "edge_type": "refers_to"})

    corpus_count = write_jsonl(args.output, final_rows)
    edge_count = write_jsonl(args.edges_output, edge_rows)
    LOGGER.info("Wrote %d corpus rows -> %s", corpus_count, args.output)
    LOGGER.info("Wrote %d edges -> %s", edge_count, args.edges_output)
    LOGGER.info(
        "mode=%s updated_tags=%d removed_tags=%d",
        "incremental" if args.incremental else "full",
        updated_tags,
        removed_tags,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
